name: Build and Push main

on:
  push:
    branches:
      - main
      - DEV-**
      # paths-ignore:
      #   - '.github/**'
      #   - '.git/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64]
        registry: ['dockerhub', 'ghcr']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set IMAGE_TAG_SHA
        run: echo "IMAGE_TAG_SHA=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          IMAGE_NAME="kubiya/base-agent:${{ env.IMAGE_TAG_SHA }}"
          docker buildx build \
            --platform ${{ matrix.platform }} \
            --tag $IMAGE_NAME \
            --load .

      # Docker Hub
      - name: Login to Docker Hub
        if: ${{ matrix.registry == 'dockerhub' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        if: ${{ matrix.registry == 'dockerhub' }}
        run: |
          IMAGE_NAME="kubiya/base-agent:${{ env.IMAGE_TAG_SHA }}"
          docker push $IMAGE_NAME

      # GitHub Container Registry
      - name: Login to GHCR
        if: ${{ matrix.registry == 'ghcr' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GHCR
        if: ${{ matrix.registry == 'ghcr' }}
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/kubiya-agent:${{ env.IMAGE_TAG_SHA }}"
          docker push $IMAGE_NAME
      