name: Build and Push main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64]
        registry: ['dockerhub', 'ghcr']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set DOCKER_IMAGE_NAME
        run: echo "DOCKER_IMAGE_NAME=kubiya/base-agent:stable" >> $GITHUB_ENV
      
      - name: Set GHCR_IMAGE_NAME
        run: echo "GHCR_IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/kubiya-agent:stable" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker buildx build \
            --platform ${{ matrix.platform }} \
            --tag $DOCKER_IMAGE_NAME \
            --tag $GHCR_IMAGE_NAME \
            --tag 'kubiya/base-agent:latest' \
            --load .

      # Docker Hub
      - name: Login to Docker Hub
        if: ${{ matrix.registry == 'dockerhub' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        if: ${{ matrix.registry == 'dockerhub' }}
        run: |
          docker push $DOCKER_IMAGE_NAME

      # GitHub Container Registry
      - name: Login to GHCR
        if: ${{ matrix.registry == 'ghcr' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_GITHUB_TOKEN }}

      - name: Push to GHCR
        if: ${{ matrix.registry == 'ghcr' }}
        run: |
          docker push $GHCR_IMAGE_NAME
      
